#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build the QPedia Featured Images plugin folder + installable zip from images-featured-webp/."""
import os
import re
import shutil
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'images-featured-webp')
DST = os.path.join(ROOT, 'qpedia-featured-images')
IMGDIR = os.path.join(DST, 'images')
ZIP = os.path.join(ROOT, 'qpedia-featured-images.zip')

# slugs that have no webp of their own -> reuse another file
EXTRAS = {
    'quantum-alternative-medicine-science-2': 'quantum-alternative-medicine-science.webp',
}


def main():
    files = sorted(f for f in os.listdir(SRC) if f.lower().endswith('.webp'))
    assert files, 'no webp files found'
    manifest = {}  # slug -> file
    for f in files:
        with open(os.path.join(SRC, f), 'rb') as fh:
            head = fh.read(12)
        assert head[:4] == b'RIFF' and head[8:12] == b'WEBP', 'not a webp: ' + f
        slug = f[:-5]
        assert re.fullmatch(r'[a-z0-9-]+', slug), 'bad slug: ' + slug
        manifest[slug] = f
    for slug, f in EXTRAS.items():
        assert f in manifest.values(), 'extra target missing: ' + f
        manifest[slug] = f

    os.makedirs(DST, exist_ok=True)

    # manifest.php
    lines = [
        '<?php',
        '// Generated by tools/build_featured_plugin.py - do not edit.',
        '// slug => bundled webp file (images/)',
        'return array(',
    ]
    for slug in sorted(manifest):
        lines.append("    '%s' => '%s'," % (slug, manifest[slug]))
    lines.append(');')
    with open(os.path.join(DST, 'manifest.php'), 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(lines) + '\n')

    # copy images
    os.makedirs(IMGDIR, exist_ok=True)
    for f in files:
        shutil.copy2(os.path.join(SRC, f), os.path.join(IMGDIR, f))

    # zip
    members = []
    for name in ('qpedia-featured-images.php', 'manifest.php', 'README.md'):
        p = os.path.join(DST, name)
        assert os.path.exists(p), 'missing ' + p
        members.append((p, os.path.join('qpedia-featured-images', name)))
    for f in files:
        members.append((os.path.join(IMGDIR, f), os.path.join('qpedia-featured-images', 'images', f)))
    if os.path.exists(ZIP):
        os.remove(ZIP)
    with zipfile.ZipFile(ZIP, 'w', zipfile.ZIP_DEFLATED) as z:
        for src, arc in members:
            z.write(src, arc)

    print('manifest entries:', len(manifest))
    print('images:', len(files))
    print('zip:', ZIP, os.path.getsize(ZIP), 'bytes')

    with zipfile.ZipFile(ZIP) as z:
        bad = z.testzip()
        assert bad is None, 'corrupt member: ' + str(bad)
        print('zip members:', len(z.namelist()), 'OK')


if __name__ == '__main__':
    main()
